import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.knowledgeResources': 'Knowledge & Resources',
    'nav.tools': 'Tools',
    'nav.stakeholderEngagement': 'Stakeholder Engagement',
    'nav.benefits': 'Benefits',
    'nav.charging': 'Charging',
    'nav.simulator': 'Simulator',
    'nav.sustainability': 'Sustainability',
    'nav.evse': 'EVSE',
    'nav.vehicleSelection': 'Vehicle Selection',
    'nav.language': 'Language',
    
    // Common
    'common.evAwareness': 'EV Awareness Hub',
    'common.learnMore': 'Learn More',
    'common.getStarted': 'Get Started',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.reset': 'Reset',
    'common.clear': 'CLEAR',
    'common.save': 'SAVE CONFIG',
    'common.start': 'START SIMULATION',
    'common.showSpecs': 'Show Specifications',
    'common.customEntry': 'Custom Entry',
    
    // Hero Section
    'hero.title': 'Welcome to the Future of',
    'hero.titleHighlight': 'Electric Mobility',
    'hero.mainTitle': 'Drive the Future. Sustainably.',
    'hero.subtitle': 'Discover how electric vehicles are revolutionizing transportation and creating a cleaner, greener tomorrow.',
    'hero.exploreButton': 'Explore Benefits',
    'hero.simulatorButton': 'Try the Charging Simulator',
    
    // Benefits Section
    'benefits.title': 'Why Choose Electric?',
    'benefits.subtitle': 'Electric vehicles offer compelling advantages that go beyond just environmental benefits.',
    'benefits.environmental.title': 'Environmental Impact',
    'benefits.environmental.desc': 'Zero tailpipe emissions mean cleaner air and reduced carbon footprint for a healthier planet.',
    'benefits.cost.title': 'Cost Savings',
    'benefits.cost.desc': 'Lower fuel and maintenance costs save thousands over the vehicle\'s lifetime.',
    'benefits.performance.title': 'Superior Performance',
    'benefits.performance.desc': 'Instant torque delivery provides smooth, powerful acceleration and a thrilling driving experience.',
    'benefits.tech.title': 'Advanced Technology',
    'benefits.tech.desc': 'Cutting-edge features and smart connectivity',
    'benefits.convenience.title': 'Convenience',
    'benefits.convenience.desc': 'Charge at home overnight and wake up to a full battery every morning.',
    
    // Charging Section
    'charging.title': 'Understanding EV Charging',
    'charging.subtitle': 'Learn about different charging levels and their benefits',
    'charging.level1.title': 'Level 1 Charging',
    'charging.level1.power': '120V / 1.4 kW',
    'charging.level1.time': '40-50 hours',
    'charging.level1.desc': 'Perfect for overnight charging at home',
    'charging.level2.title': 'Level 2 Charging',
    'charging.level2.power': '240V / 11.5 kW',
    'charging.level2.time': '4-10 hours',
    'charging.level2.desc': 'Ideal for home and workplace charging',
    'charging.dcfast.title': 'DC Fast Charging',
    'charging.dcfast.power': '400V / 50-350 kW',
    'charging.dcfast.time': '20-60 minutes',
    'charging.dcfast.desc': 'Quick charging for long trips',
    
    // Charging Systems Section
    'chargingSystems.title': 'Understanding Charging Systems',
    'chargingSystems.subtitle': 'Different charging levels offer flexibility for various needs and locations.',
    'chargingSystems.powerOutput': 'Power Output',
    'chargingSystems.chargeTime': 'Charge Time',
    'chargingSystems.level1Title': 'Level 1 Charging',
    'chargingSystems.level1Subtitle': 'Standard Home Outlet',
    'chargingSystems.level1Power': '1.4 - 1.9 kW',
    'chargingSystems.level1Time': '40-50 hours for full charge',
    'chargingSystems.level1Desc': 'Uses a standard 120V household outlet. Perfect for overnight charging at home with minimal installation required.',
    'chargingSystems.level1Feature1': 'No special installation',
    'chargingSystems.level1Feature2': 'Works anywhere',
    'chargingSystems.level1Feature3': 'Best for plug-in hybrids',
    'chargingSystems.level2Title': 'Level 2 Charging',
    'chargingSystems.level2Subtitle': 'Dedicated Home/Public Charger',
    'chargingSystems.level2Power': '7 - 19 kW',
    'chargingSystems.level2Time': '4-10 hours for full charge',
    'chargingSystems.level2Desc': 'Requires a 240V outlet, similar to what\'s used for electric dryers. Most common for home and public charging.',
    'chargingSystems.level2Feature1': 'Professional installation',
    'chargingSystems.level2Feature2': 'Faster charging',
    'chargingSystems.level2Feature3': 'Ideal for daily use',
    'chargingSystems.dcFastTitle': 'DC Fast Charging',
    'chargingSystems.dcFastSubtitle': 'Highway & Commercial Stations',
    'chargingSystems.dcFastPower': '50 - 350 kW',
    'chargingSystems.dcFastTime': '20-60 minutes to 80%',
    'chargingSystems.dcFastDesc': 'Ultra-fast charging for long trips. Bypasses onboard charger to deliver DC power directly to the battery.',
    'chargingSystems.dcFastFeature1': 'Rapid charging',
    'chargingSystems.dcFastFeature2': 'Long-distance travel',
    'chargingSystems.dcFastFeature3': 'Commercial locations',
    
    // Sustainability Section
    'sustainability.title': 'Driving Sustainability Forward',
    'sustainability.subtitle': 'Electric vehicles are more than just cars—they\'re a commitment to a cleaner future. By choosing electric, you\'re actively reducing your carbon footprint and contributing to a more sustainable world.',
    'sustainability.renewable.title': 'Renewable Energy',
    'sustainability.renewable.desc': 'EVs paired with solar and wind power create a truly sustainable transportation system',
    'sustainability.emissions.title': 'Zero Emissions',
    'sustainability.emissions.desc': 'Electric vehicles produce no tailpipe emissions, improving air quality in urban areas',
    'sustainability.stat1Unit': 'lbs',
    'sustainability.stat1Label': 'CO₂ Reduced Annually',
    'sustainability.stat2Label': 'Fuel Savings Per Year',
    'sustainability.stat3Label': 'Renewable Energy Compatible',
    'sustainability.imageAlt': 'Renewable Energy',
    
    // Footer
    'footer.tagline': 'Empowering the transition to sustainable transportation through education and innovation.',
    'footer.about': 'About',
    'footer.aboutUs': 'About Us',
    'footer.contact': 'Contact',
    'footer.careers': 'Careers',
    'footer.resources': 'Resources',
    'footer.blog': 'Blog',
    'footer.guides': 'Guides',
    'footer.faq': 'FAQ',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.rights': 'All rights reserved.',
    'footer.quickLinks': 'Quick Links',
    'footer.stayUpdated': 'Stay Updated',
    'footer.emailPlaceholder': 'Enter your email',
    'footer.subscribe': 'Subscribe',
    'footer.poweredBy': 'Powered by clean energy data',
    'footer.copyright': '© 2025 EV Awareness Hub. All rights reserved. Driving towards a sustainable future.',
    'footer.successTitle': 'Success!',
    'footer.successDesc': 'You\'ve been subscribed to our newsletter.',
    
    // EVSE Page
    'evse.title': 'EVSE Installation Assessment Tool',
    'evse.subtitle': 'A live calculator to evaluate your home\'s electrical readiness.',
    'evse.sectionA': 'Section A: Your Electrical Service',
    'evse.mainBreaker': 'Main breaker rating:',
    'evse.breakerSpaces': 'Available breaker spaces:',
    'evse.spacesAvailable': '2+ spaces available',
    'evse.panelFull': 'Panel full',
    'evse.sectionB': 'Section B: Existing Home Loads',
    'evse.livingArea': 'Approximate heated living area:',
    'evse.loadInventory': 'Major 240V Load Inventory',
    'evse.range': 'Electric range/cooktop:',
    'evse.waterHeater': 'Electric water heater:',
    'evse.dryer': 'Electric dryer:',
    'evse.hvac': 'HVAC (AC or Heat Pump):',
    'evse.heating': 'Electric heating (Baseboards):',
    'evse.other': 'Other 240V Loads (Hot Tub, etc.):',
    'evse.noGas': 'No (or Gas)',
    'evse.rating': 'Rating (kW):',
    'evse.ratingAmps': 'Rating (Amps at 240V):',
    'evse.totalRating': 'Total Rating (kW):',
    'evse.sectionC': 'Section C: EV Charger Details',
    'evse.chargerAmps': 'Charger amperage rating:',
    'evse.selectCharger': 'Select charger amps',
    'evse.distance': 'Distance from panel (feet):',
    'evse.structure': 'Is location a separate structure (detached building)?',
    'evse.structureYes': 'Yes (requires 4-wire feeder + ground rod)',
    'evse.structureNo': 'No (attached or subpanel option)',
    'evse.livePanelCapacity': 'Live Panel Capacity',
    'evse.totalLoad': 'Total Load:',
    'evse.service': 'Service:',
    'evse.safeLimit': 'Safe Limit:',
    'evse.recommendation': 'Recommendation',
    'evse.checklist': 'Checklist for Electrician',
    'evse.mainService': 'Main Service:',
    'evse.existingLoad': 'Existing Load:',
    'evse.charger': 'Charger:',
    'evse.reqBreaker': 'Req. Breaker:',
    'evse.reqWire': 'Req. Wire:',
    'evse.emsNeeded': 'EMS Needed:',
    'evse.upgradeNeeded': 'Upgrade Needed:',
    'evse.resetForm': 'Reset Form',
    'evse.selectChargerMsg': 'Select a Charger',
    'evse.selectChargerDesc': 'Please select a charger amperage to see your recommendation.',
    'evse.panelSpaceFull': 'Panel Space: FULL',
    'evse.panelSpaceFullDesc': 'Your panel is full. You will need a solution from your electrician, such as a subpanel or using tandem breakers.',
    'evse.serviceAdequate': 'Service Adequate',
    'evse.serviceAdequateDesc': 'Your service has capacity for this charger. No upgrades or EMS are required.',
    'evse.upgradeRequired': 'Service Upgrade Required',
    'evse.upgradeRequiredDesc': 'Your service is overloaded. An EMS is likely not enough; a service upgrade is recommended.',
    'evse.emsRecommended': 'EMS Recommended',
    'evse.emsRecommendedDesc': 'Your service is overloaded. An EMS is strongly recommended to avoid a costly service upgrade.',
    
    // Vehicle Selection Page
    'vehicle.title': 'VEHICLE SELECTION',
    'vehicle.makeLabel': 'Vehicle Make',
    'vehicle.selectMake': 'Select a make...',
    'vehicle.modelLabel': 'Model/Variant',
    'vehicle.selectModel': 'Select a model...',
    'vehicle.selectMakeFirst': 'Select a make first...',
    'vehicle.yearLabel': 'Production Year',
    'vehicle.summary': 'Vehicle Summary (Auto-populated):',
    'vehicle.summaryPlaceholder': 'Select a vehicle model to see its specifications.',
    'vehicle.chargerSection': 'CHARGER SELECTION',
    'vehicle.chargingLevel': 'Charging Level',
    'vehicle.level1': 'Level 1',
    'vehicle.level2': 'Level 2',
    'vehicle.dcfast': 'DC Fast',
    'vehicle.level2Options': 'Level 2 Options',
    'vehicle.powerRating': 'Power Rating',
    'vehicle.chargerCooling': 'Charger Cooling',
    'vehicle.passive': 'Passive (no fan)',
    'vehicle.active': 'Active (fan/liquid)',
    'vehicle.dcfastOptions': 'DC Fast Options',
    'vehicle.connectorType': 'Connector Type',
    'vehicle.envConditions': 'ENVIRONMENTAL CONDITIONS',
    'vehicle.ambientTemp': 'Ambient Temperature:',
    'vehicle.winterMode': '⚠️ Winter mode (5°C)',
    'vehicle.simParameters': 'SIMULATION PARAMETERS',
    'vehicle.startingSoc': 'Starting SoC:',
    'vehicle.targetSoc': 'Target SoC:',
    'vehicle.cvPhase': '(If >80%, shows CV phase only)',
    'vehicle.timeWarning': '⚠️ To 100% may add 40-50% time',
    'vehicle.timeResolution': 'Time Resolution',
    'vehicle.standard': 'Standard (1 min steps)',
    'vehicle.high': 'High (10 sec)',
    'vehicle.recommend': '◄ Recommend',
    
    // About Page
    'about.pageTitle': 'About Us',
    'about.pageSubtitle': 'Learn about our mission to accelerate the adoption of electric vehicles and create a sustainable future for transportation.',
    'about.projectTitle': 'About the Project',
    'about.projectDesc1': 'The EV Awareness Hub project is dedicated to educating and empowering individuals, businesses, and communities to embrace electric vehicle technology. Our comprehensive platform provides the tools, knowledge, and resources needed to make informed decisions about transitioning to electric mobility.',
    'about.projectDesc2': 'Through interactive simulators, educational content, and practical guides, we aim to demystify electric vehicles and make the transition to sustainable transportation accessible to everyone. Our goal is to accelerate the adoption of EVs by addressing common concerns and providing clear, actionable information.',
    'about.objectivesTitle': 'Objectives',
    'about.objective1': 'Educate the public about the benefits, technology, and practicalities of electric vehicles through accessible and engaging content.',
    'about.objective2': 'Provide interactive tools and simulators that help users understand charging requirements, costs, and vehicle specifications.',
    'about.objective3': 'Support the transition to sustainable transportation by offering resources for home charging installation and infrastructure planning.',
    'about.objective4': 'Build a community of EV advocates and stakeholders to share knowledge and drive collective action towards a greener future.',
    'about.partnersTitle': 'Partners',
    'about.partnersDesc': 'We collaborate with leading organizations, institutions, and industry partners to deliver accurate information and innovative solutions for electric mobility.',
    'about.partner1Name': 'Research Institutions',
    'about.partner1Desc': 'Academic partners providing cutting-edge research and data on EV technology and sustainability.',
    'about.partner2Name': 'Industry Partners',
    'about.partner2Desc': 'Automotive manufacturers and charging infrastructure providers supporting our educational mission.',
    'about.partner3Name': 'Government Agencies',
    'about.partner3Desc': 'Public sector partners helping to promote policies and incentives for EV adoption.',
    
    // Quick Links Section
    'quickLinks.sectionTitle': 'Explore Our Platform',
    'quickLinks.sectionSubtitle': 'Access insights, interactive tools, and real impact data to guide your EV journey.',
    'quickLinks.insightsTitle': 'Insights',
    'quickLinks.insightsDesc': 'Discover the latest research and knowledge about electric vehicles.',
    'quickLinks.insightsFeature1': 'EV Benefits & Advantages',
    'quickLinks.insightsFeature2': 'Charging Technology Guide',
    'quickLinks.insightsFeature3': 'Sustainability Impact',
    'quickLinks.toolsTitle': 'Interactive Tools',
    'quickLinks.toolsDesc': 'Use our simulators and calculators to plan your EV transition.',
    'quickLinks.toolsFeature1': 'Charging Simulator',
    'quickLinks.toolsFeature2': 'EVSE Installation Calculator',
    'quickLinks.toolsFeature3': 'Vehicle Selection Tool',
    'quickLinks.statsTitle': 'Impact Statistics',
    'quickLinks.statsDesc': 'See the real environmental and economic impact of electric vehicles.',
    'quickLinks.stat1Label': 'Lower Fuel Costs',
    'quickLinks.stat2Label': 'Less Maintenance',
    'quickLinks.stat3Label': 'Emissions',
    'quickLinks.exploreMore': 'Explore More',
    
    // Knowledge Page
    'knowledge.label': 'Learning Center',
    'knowledge.pageTitle': 'Knowledge & Resources',
    'knowledge.pageSubtitle': 'Everything you need to know about electric vehicles, charging infrastructure, and sustainable transportation.',
    'knowledge.topicsTitle': 'Explore Topics',
    'knowledge.basicsTitle': 'EV Basics',
    'knowledge.basicsDesc': 'Understand the fundamentals of electric vehicles and how they work.',
    'knowledge.basicsArticle1': 'How electric motors work',
    'knowledge.basicsArticle2': 'Battery technology explained',
    'knowledge.basicsArticle3': 'EV vs. hybrid vs. plug-in hybrid',
    'knowledge.chargingTitle': 'Charging Guide',
    'knowledge.chargingDesc': 'Learn about different charging levels, connectors, and best practices.',
    'knowledge.chargingArticle1': 'Level 1, 2, and DC fast charging',
    'knowledge.chargingArticle2': 'Home charging installation',
    'knowledge.chargingArticle3': 'Public charging networks',
    'knowledge.envTitle': 'Environmental Impact',
    'knowledge.envDesc': 'Discover how EVs contribute to a cleaner, greener future.',
    'knowledge.envArticle1': 'Carbon footprint comparison',
    'knowledge.envArticle2': 'Lifecycle emissions analysis',
    'knowledge.envArticle3': 'Renewable energy integration',
    'knowledge.costsTitle': 'Costs & Savings',
    'knowledge.costsDesc': 'Understand the total cost of ownership and potential savings.',
    'knowledge.costsArticle1': 'Purchase price vs. fuel savings',
    'knowledge.costsArticle2': 'Maintenance cost comparison',
    'knowledge.costsArticle3': 'Incentives and rebates',
    'knowledge.resourcesTitle': 'Featured Resources',
    'knowledge.resource1Title': 'EV Charging Basics',
    'knowledge.resource1Desc': 'A concise overview of how Level 1, Level 2 and DC fast charging work and what consumers should expect when charging at home or in public.',
    'knowledge.resource1Button': 'View Guide',
    'knowledge.resource2Title': 'Level 2 Charging Misconceptions',
    'knowledge.resource2Desc': 'Clarifies common myths about installing a Level 2 EV charger and electrical upgrades in Canada.',
    'knowledge.resource2Button': 'Learn More',
    'knowledge.resource3Title': 'More Resources Coming Soon',
    'knowledge.resource3Desc': 'Additional guides and briefs are in development. Check back soon for new resources.',
    'knowledge.faqTitle': 'Have Questions?',
    'knowledge.faqDesc': 'Find answers to common questions about electric vehicles and our platform.',
    'knowledge.faqButton': 'Learn More About Us',
    
    // Stakeholder Page
    'stakeholder.label': 'Community',
    'stakeholder.pageTitle': 'Stakeholder Engagement',
    'stakeholder.pageSubtitle': 'Connecting with communities, industries, and institutions to accelerate the transition to electric mobility.',
    'stakeholder.groupsTitle': 'Who We Serve',
    'stakeholder.consumersTitle': 'Consumers & EV Owners',
    'stakeholder.consumersDesc': 'Empowering individuals with knowledge and tools to make informed decisions about electric vehicles.',
    'stakeholder.consumersPoint1': 'Access to charging simulators and cost calculators',
    'stakeholder.consumersPoint2': 'Educational resources on EV technology',
    'stakeholder.consumersPoint3': 'Home charging installation guidance',
    'stakeholder.industryTitle': 'Industry Partners',
    'stakeholder.industryDesc': 'Collaborating with automotive and energy sectors to advance EV adoption.',
    'stakeholder.industryPoint1': 'Infrastructure planning tools',
    'stakeholder.industryPoint2': 'Research collaboration opportunities',
    'stakeholder.industryPoint3': 'Data-driven insights on EV trends',
    'stakeholder.educationTitle': 'Educational Institutions',
    'stakeholder.educationDesc': 'Supporting academic research and training the next generation of EV experts.',
    'stakeholder.educationPoint1': 'Curriculum development resources',
    'stakeholder.educationPoint2': 'Research partnership programs',
    'stakeholder.educationPoint3': 'Student engagement initiatives',
    'stakeholder.governmentTitle': 'Government & Policy Makers',
    'stakeholder.governmentDesc': 'Providing data and insights to support evidence-based EV policies.',
    'stakeholder.governmentPoint1': 'Impact assessment tools',
    'stakeholder.governmentPoint2': 'Infrastructure planning support',
    'stakeholder.governmentPoint3': 'Policy recommendation resources',
    'stakeholder.involvedTitle': 'Get Involved',
    'stakeholder.feedbackTitle': 'Share Your Feedback',
    'stakeholder.feedbackDesc': 'Help us improve our platform by sharing your experience and suggestions.',
    'stakeholder.feedbackButton': 'Contact Us',
    'stakeholder.partnerTitle': 'Partner With Us',
    'stakeholder.partnerDesc': 'Interested in collaborating on EV research or educational initiatives?',
    'stakeholder.partnerButton': 'Visit Smart Grid Lab',
    'stakeholder.ctaTitle': 'Ready to Make an Impact?',
    'stakeholder.ctaDesc': 'Explore our resources and tools to start your journey towards sustainable transportation.',
    'stakeholder.ctaButton': 'Explore Resources',
  },
  fr: {
    // Navbar
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.knowledgeResources': 'Connaissances et Ressources',
    'nav.tools': 'Outils',
    'nav.stakeholderEngagement': 'Engagement des Parties Prenantes',
    'nav.benefits': 'Avantages',
    'nav.charging': 'Recharge',
    'nav.simulator': 'Simulateur',
    'nav.sustainability': 'Durabilité',
    'nav.evse': 'EVSE',
    'nav.vehicleSelection': 'Sélection de véhicule',
    'nav.language': 'Langue',
    
    // Common
    'common.evAwareness': 'Carrefour EV Awareness',
    'common.learnMore': 'En savoir plus',
    'common.getStarted': 'Commencer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.reset': 'Réinitialiser',
    'common.clear': 'EFFACER',
    'common.save': 'ENREGISTRER LA CONFIG',
    'common.start': 'DÉMARRER LA SIMULATION',
    'common.showSpecs': 'Afficher les spécifications',
    'common.customEntry': 'Entrée personnalisée',
    
    // Hero Section
    'hero.title': 'Bienvenue dans le futur de la',
    'hero.titleHighlight': 'Mobilité Électrique',
    'hero.mainTitle': 'Conduisez le futur. Durablement.',
    'hero.subtitle': 'Découvrez comment les véhicules électriques révolutionnent le transport et créent un avenir plus propre et plus vert.',
    'hero.exploreButton': 'Explorer les avantages',
    'hero.simulatorButton': 'Essayer le simulateur de recharge',
    
    // Benefits Section
    'benefits.title': 'Pourquoi choisir l\'électrique?',
    'benefits.subtitle': 'Les véhicules électriques offrent des avantages convaincants qui vont au-delà des bénéfices environnementaux.',
    'benefits.environmental.title': 'Impact environnemental',
    'benefits.environmental.desc': 'Zéro émission signifie un air plus propre et une empreinte carbone réduite pour une planète plus saine.',
    'benefits.cost.title': 'Économies',
    'benefits.cost.desc': 'Des coûts de carburant et d\'entretien réduits permettent d\'économiser des milliers sur la durée de vie du véhicule.',
    'benefits.performance.title': 'Performance supérieure',
    'benefits.performance.desc': 'Le couple instantané offre une accélération douce et puissante pour une expérience de conduite exaltante.',
    'benefits.tech.title': 'Technologie avancée',
    'benefits.tech.desc': 'Fonctionnalités de pointe et connectivité intelligente',
    'benefits.convenience.title': 'Commodité',
    'benefits.convenience.desc': 'Rechargez à domicile pendant la nuit et réveillez-vous avec une batterie pleine chaque matin.',
    
    // Charging Section
    'charging.title': 'Comprendre la recharge des VE',
    'charging.subtitle': 'Découvrez les différents niveaux de recharge et leurs avantages',
    'charging.level1.title': 'Recharge Niveau 1',
    'charging.level1.power': '120V / 1,4 kW',
    'charging.level1.time': '40-50 heures',
    'charging.level1.desc': 'Parfait pour la recharge nocturne à domicile',
    'charging.level2.title': 'Recharge Niveau 2',
    'charging.level2.power': '240V / 11,5 kW',
    'charging.level2.time': '4-10 heures',
    'charging.level2.desc': 'Idéal pour la recharge à domicile et au travail',
    'charging.dcfast.title': 'Recharge rapide DC',
    'charging.dcfast.power': '400V / 50-350 kW',
    'charging.dcfast.time': '20-60 minutes',
    'charging.dcfast.desc': 'Recharge rapide pour les longs trajets',
    
    // Charging Systems Section
    'chargingSystems.title': 'Comprendre les systèmes de recharge',
    'chargingSystems.subtitle': 'Différents niveaux de recharge offrent une flexibilité pour divers besoins et emplacements.',
    'chargingSystems.powerOutput': 'Puissance de sortie',
    'chargingSystems.chargeTime': 'Temps de recharge',
    'chargingSystems.level1Title': 'Recharge Niveau 1',
    'chargingSystems.level1Subtitle': 'Prise domestique standard',
    'chargingSystems.level1Power': '1,4 - 1,9 kW',
    'chargingSystems.level1Time': '40-50 heures pour une charge complète',
    'chargingSystems.level1Desc': 'Utilise une prise domestique standard 120V. Parfait pour la recharge nocturne à domicile avec une installation minimale requise.',
    'chargingSystems.level1Feature1': 'Pas d\'installation spéciale',
    'chargingSystems.level1Feature2': 'Fonctionne partout',
    'chargingSystems.level1Feature3': 'Idéal pour les hybrides rechargeables',
    'chargingSystems.level2Title': 'Recharge Niveau 2',
    'chargingSystems.level2Subtitle': 'Chargeur dédié domicile/public',
    'chargingSystems.level2Power': '7 - 19 kW',
    'chargingSystems.level2Time': '4-10 heures pour une charge complète',
    'chargingSystems.level2Desc': 'Nécessite une prise 240V, similaire à celle utilisée pour les sécheuses électriques. Le plus courant pour la recharge à domicile et publique.',
    'chargingSystems.level2Feature1': 'Installation professionnelle',
    'chargingSystems.level2Feature2': 'Recharge plus rapide',
    'chargingSystems.level2Feature3': 'Idéal pour l\'usage quotidien',
    'chargingSystems.dcFastTitle': 'Recharge rapide DC',
    'chargingSystems.dcFastSubtitle': 'Stations autoroutières et commerciales',
    'chargingSystems.dcFastPower': '50 - 350 kW',
    'chargingSystems.dcFastTime': '20-60 minutes jusqu\'à 80%',
    'chargingSystems.dcFastDesc': 'Recharge ultra-rapide pour les longs trajets. Contourne le chargeur embarqué pour délivrer l\'énergie DC directement à la batterie.',
    'chargingSystems.dcFastFeature1': 'Recharge rapide',
    'chargingSystems.dcFastFeature2': 'Voyages longue distance',
    'chargingSystems.dcFastFeature3': 'Emplacements commerciaux',
    
    // Sustainability Section
    'sustainability.title': 'Conduire la durabilité',
    'sustainability.subtitle': 'Les véhicules électriques sont plus que de simples voitures—c\'est un engagement envers un avenir plus propre. En choisissant l\'électrique, vous réduisez activement votre empreinte carbone et contribuez à un monde plus durable.',
    'sustainability.renewable.title': 'Énergie renouvelable',
    'sustainability.renewable.desc': 'Les VE associés à l\'énergie solaire et éolienne créent un système de transport vraiment durable',
    'sustainability.emissions.title': 'Zéro émission',
    'sustainability.emissions.desc': 'Les véhicules électriques ne produisent aucune émission, améliorant la qualité de l\'air en zones urbaines',
    'sustainability.stat1Unit': 'lbs',
    'sustainability.stat1Label': 'CO₂ réduit annuellement',
    'sustainability.stat2Label': 'Économies de carburant par an',
    'sustainability.stat3Label': 'Compatible énergie renouvelable',
    'sustainability.imageAlt': 'Énergie renouvelable',
    
    // Footer
    'footer.tagline': 'Faciliter la transition vers un transport durable grâce à l\'éducation et l\'innovation.',
    'footer.about': 'À propos',
    'footer.aboutUs': 'À propos de nous',
    'footer.contact': 'Contact',
    'footer.careers': 'Carrières',
    'footer.resources': 'Ressources',
    'footer.blog': 'Blog',
    'footer.guides': 'Guides',
    'footer.faq': 'FAQ',
    'footer.legal': 'Juridique',
    'footer.privacy': 'Politique de confidentialité',
    'footer.terms': 'Conditions d\'utilisation',
    'footer.rights': 'Tous droits réservés.',
    'footer.quickLinks': 'Liens rapides',
    'footer.stayUpdated': 'Restez informé',
    'footer.emailPlaceholder': 'Entrez votre email',
    'footer.subscribe': 'S\'abonner',
    'footer.poweredBy': 'Propulsé par des données d\'énergie propre',
    'footer.copyright': '© 2025 EV Awareness Hub. Tous droits réservés. Vers un avenir durable.',
    'footer.successTitle': 'Succès!',
    'footer.successDesc': 'Vous êtes maintenant abonné à notre newsletter.',
    
    // EVSE Page
    'evse.title': 'Outil d\'évaluation d\'installation EVSE',
    'evse.subtitle': 'Un calculateur en direct pour évaluer la préparation électrique de votre maison.',
    'evse.sectionA': 'Section A : Votre service électrique',
    'evse.mainBreaker': 'Puissance du disjoncteur principal :',
    'evse.breakerSpaces': 'Espaces disponibles pour disjoncteurs :',
    'evse.spacesAvailable': '2+ espaces disponibles',
    'evse.panelFull': 'Panneau plein',
    'evse.sectionB': 'Section B : Charges domestiques existantes',
    'evse.livingArea': 'Surface habitable chauffée approximative :',
    'evse.loadInventory': 'Inventaire des charges 240V majeures',
    'evse.range': 'Cuisinière/table de cuisson électrique :',
    'evse.waterHeater': 'Chauffe-eau électrique :',
    'evse.dryer': 'Sécheuse électrique :',
    'evse.hvac': 'CVCA (Climatisation ou pompe à chaleur) :',
    'evse.heating': 'Chauffage électrique (plinthes) :',
    'evse.other': 'Autres charges 240V (spa, etc.) :',
    'evse.noGas': 'Non (ou gaz)',
    'evse.rating': 'Puissance (kW) :',
    'evse.ratingAmps': 'Puissance (Ampères à 240V) :',
    'evse.totalRating': 'Puissance totale (kW) :',
    'evse.sectionC': 'Section C : Détails du chargeur VE',
    'evse.chargerAmps': 'Ampérage du chargeur :',
    'evse.selectCharger': 'Sélectionner l\'ampérage du chargeur',
    'evse.distance': 'Distance du panneau (pieds) :',
    'evse.structure': 'L\'emplacement est-il une structure séparée (bâtiment détaché) ?',
    'evse.structureYes': 'Oui (nécessite un câble 4 fils + tige de mise à la terre)',
    'evse.structureNo': 'Non (option annexe ou sous-panneau)',
    'evse.livePanelCapacity': 'Capacité du panneau en direct',
    'evse.totalLoad': 'Charge totale :',
    'evse.service': 'Service :',
    'evse.safeLimit': 'Limite sûre :',
    'evse.recommendation': 'Recommandation',
    'evse.checklist': 'Liste de vérification pour l\'électricien',
    'evse.mainService': 'Service principal :',
    'evse.existingLoad': 'Charge existante :',
    'evse.charger': 'Chargeur :',
    'evse.reqBreaker': 'Disjoncteur req. :',
    'evse.reqWire': 'Câble req. :',
    'evse.emsNeeded': 'SGE nécessaire :',
    'evse.upgradeNeeded': 'Mise à niveau nécessaire :',
    'evse.resetForm': 'Réinitialiser le formulaire',
    'evse.selectChargerMsg': 'Sélectionner un chargeur',
    'evse.selectChargerDesc': 'Veuillez sélectionner un ampérage de chargeur pour voir votre recommandation.',
    'evse.panelSpaceFull': 'Espace panneau : PLEIN',
    'evse.panelSpaceFullDesc': 'Votre panneau est plein. Vous aurez besoin d\'une solution de votre électricien, comme un sous-panneau ou l\'utilisation de disjoncteurs tandem.',
    'evse.serviceAdequate': 'Service adéquat',
    'evse.serviceAdequateDesc': 'Votre service a la capacité pour ce chargeur. Aucune mise à niveau ou SGE n\'est requise.',
    'evse.upgradeRequired': 'Mise à niveau du service requise',
    'evse.upgradeRequiredDesc': 'Votre service est surchargé. Un SGE ne suffit probablement pas; une mise à niveau du service est recommandée.',
    'evse.emsRecommended': 'SGE recommandé',
    'evse.emsRecommendedDesc': 'Votre service est surchargé. Un SGE est fortement recommandé pour éviter une coûteuse mise à niveau du service.',
    
    // Vehicle Selection Page
    'vehicle.title': 'SÉLECTION DE VÉHICULE',
    'vehicle.makeLabel': 'Marque du véhicule',
    'vehicle.selectMake': 'Sélectionner une marque...',
    'vehicle.modelLabel': 'Modèle/Variante',
    'vehicle.selectModel': 'Sélectionner un modèle...',
    'vehicle.selectMakeFirst': 'Sélectionner d\'abord une marque...',
    'vehicle.yearLabel': 'Année de production',
    'vehicle.summary': 'Résumé du véhicule (remplissage automatique) :',
    'vehicle.summaryPlaceholder': 'Sélectionnez un modèle de véhicule pour voir ses spécifications.',
    'vehicle.chargerSection': 'SÉLECTION DU CHARGEUR',
    'vehicle.chargingLevel': 'Niveau de recharge',
    'vehicle.level1': 'Niveau 1',
    'vehicle.level2': 'Niveau 2',
    'vehicle.dcfast': 'DC Rapide',
    'vehicle.level2Options': 'Options Niveau 2',
    'vehicle.powerRating': 'Puissance nominale',
    'vehicle.chargerCooling': 'Refroidissement du chargeur',
    'vehicle.passive': 'Passif (sans ventilateur)',
    'vehicle.active': 'Actif (ventilateur/liquide)',
    'vehicle.dcfastOptions': 'Options DC Rapide',
    'vehicle.connectorType': 'Type de connecteur',
    'vehicle.envConditions': 'CONDITIONS ENVIRONNEMENTALES',
    'vehicle.ambientTemp': 'Température ambiante :',
    'vehicle.winterMode': '⚠️ Mode hiver (5°C)',
    'vehicle.simParameters': 'PARAMÈTRES DE SIMULATION',
    'vehicle.startingSoc': 'SoC de départ :',
    'vehicle.targetSoc': 'SoC cible :',
    'vehicle.cvPhase': '(Si >80%, affiche uniquement la phase CV)',
    'vehicle.timeWarning': '⚠️ Jusqu\'à 100% peut ajouter 40-50% de temps',
    'vehicle.timeResolution': 'Résolution temporelle',
    'vehicle.standard': 'Standard (pas de 1 min)',
    'vehicle.high': 'Élevée (10 sec)',
    'vehicle.recommend': '◄ Recommandé',
    
    // About Page
    'about.pageTitle': 'À propos de nous',
    'about.pageSubtitle': 'Découvrez notre mission pour accélérer l\'adoption des véhicules électriques et créer un avenir durable pour le transport.',
    'about.projectTitle': 'À propos du projet',
    'about.projectDesc1': 'Le projet EV Awareness Hub est dédié à l\'éducation et à l\'autonomisation des individus, des entreprises et des communautés pour adopter la technologie des véhicules électriques. Notre plateforme complète fournit les outils, les connaissances et les ressources nécessaires pour prendre des décisions éclairées sur la transition vers la mobilité électrique.',
    'about.projectDesc2': 'Grâce à des simulateurs interactifs, du contenu éducatif et des guides pratiques, nous visons à démystifier les véhicules électriques et à rendre la transition vers un transport durable accessible à tous. Notre objectif est d\'accélérer l\'adoption des VE en répondant aux préoccupations courantes et en fournissant des informations claires et exploitables.',
    'about.objectivesTitle': 'Objectifs',
    'about.objective1': 'Éduquer le public sur les avantages, la technologie et les aspects pratiques des véhicules électriques à travers un contenu accessible et engageant.',
    'about.objective2': 'Fournir des outils interactifs et des simulateurs qui aident les utilisateurs à comprendre les exigences de recharge, les coûts et les spécifications des véhicules.',
    'about.objective3': 'Soutenir la transition vers un transport durable en offrant des ressources pour l\'installation de recharge à domicile et la planification de l\'infrastructure.',
    'about.objective4': 'Construire une communauté de défenseurs des VE et de parties prenantes pour partager les connaissances et conduire une action collective vers un avenir plus vert.',
    'about.partnersTitle': 'Partenaires',
    'about.partnersDesc': 'Nous collaborons avec des organisations de premier plan, des institutions et des partenaires industriels pour fournir des informations précises et des solutions innovantes pour la mobilité électrique.',
    'about.partner1Name': 'Institutions de recherche',
    'about.partner1Desc': 'Partenaires académiques fournissant des recherches et des données de pointe sur la technologie des VE et la durabilité.',
    'about.partner2Name': 'Partenaires industriels',
    'about.partner2Desc': 'Constructeurs automobiles et fournisseurs d\'infrastructures de recharge soutenant notre mission éducative.',
    'about.partner3Name': 'Agences gouvernementales',
    'about.partner3Desc': 'Partenaires du secteur public aidant à promouvoir les politiques et les incitations pour l\'adoption des VE.',
    
    // Quick Links Section
    'quickLinks.sectionTitle': 'Explorez Notre Plateforme',
    'quickLinks.sectionSubtitle': 'Accédez aux analyses, outils interactifs et données d\'impact pour guider votre transition vers les VE.',
    'quickLinks.insightsTitle': 'Analyses',
    'quickLinks.insightsDesc': 'Découvrez les dernières recherches et connaissances sur les véhicules électriques.',
    'quickLinks.insightsFeature1': 'Avantages des VE',
    'quickLinks.insightsFeature2': 'Guide technologie de recharge',
    'quickLinks.insightsFeature3': 'Impact sur la durabilité',
    'quickLinks.toolsTitle': 'Outils Interactifs',
    'quickLinks.toolsDesc': 'Utilisez nos simulateurs et calculateurs pour planifier votre transition VE.',
    'quickLinks.toolsFeature1': 'Simulateur de recharge',
    'quickLinks.toolsFeature2': 'Calculateur installation EVSE',
    'quickLinks.toolsFeature3': 'Outil de sélection de véhicule',
    'quickLinks.statsTitle': 'Statistiques d\'Impact',
    'quickLinks.statsDesc': 'Voyez l\'impact environnemental et économique réel des véhicules électriques.',
    'quickLinks.stat1Label': 'Moins de carburant',
    'quickLinks.stat2Label': 'Moins d\'entretien',
    'quickLinks.stat3Label': 'Émissions',
    'quickLinks.exploreMore': 'Explorer Plus',
    
    // Knowledge Page
    'knowledge.label': 'Centre d\'apprentissage',
    'knowledge.pageTitle': 'Connaissances et Ressources',
    'knowledge.pageSubtitle': 'Tout ce que vous devez savoir sur les véhicules électriques, l\'infrastructure de recharge et le transport durable.',
    'knowledge.topicsTitle': 'Explorer les sujets',
    'knowledge.basicsTitle': 'Bases des VE',
    'knowledge.basicsDesc': 'Comprendre les fondamentaux des véhicules électriques et leur fonctionnement.',
    'knowledge.basicsArticle1': 'Fonctionnement des moteurs électriques',
    'knowledge.basicsArticle2': 'Technologie des batteries expliquée',
    'knowledge.basicsArticle3': 'VE vs hybride vs hybride rechargeable',
    'knowledge.chargingTitle': 'Guide de recharge',
    'knowledge.chargingDesc': 'Découvrez les différents niveaux de recharge, connecteurs et bonnes pratiques.',
    'knowledge.chargingArticle1': 'Recharge niveau 1, 2 et rapide DC',
    'knowledge.chargingArticle2': 'Installation de recharge à domicile',
    'knowledge.chargingArticle3': 'Réseaux de recharge publics',
    'knowledge.envTitle': 'Impact environnemental',
    'knowledge.envDesc': 'Découvrez comment les VE contribuent à un avenir plus propre et plus vert.',
    'knowledge.envArticle1': 'Comparaison de l\'empreinte carbone',
    'knowledge.envArticle2': 'Analyse des émissions du cycle de vie',
    'knowledge.envArticle3': 'Intégration des énergies renouvelables',
    'knowledge.costsTitle': 'Coûts et économies',
    'knowledge.costsDesc': 'Comprendre le coût total de possession et les économies potentielles.',
    'knowledge.costsArticle1': 'Prix d\'achat vs économies de carburant',
    'knowledge.costsArticle2': 'Comparaison des coûts d\'entretien',
    'knowledge.costsArticle3': 'Incitatifs et remises',
    'knowledge.resourcesTitle': 'Ressources en vedette',
    'knowledge.resource1Title': 'Bases de la recharge VE',
    'knowledge.resource1Desc': 'Un aperçu concis du fonctionnement de la recharge niveau 1, niveau 2 et rapide DC, et ce à quoi les consommateurs doivent s\'attendre lors de la recharge à domicile ou en public.',
    'knowledge.resource1Button': 'Voir le guide',
    'knowledge.resource2Title': 'Idées reçues sur la recharge niveau 2',
    'knowledge.resource2Desc': 'Clarifie les mythes courants sur l\'installation d\'un chargeur VE niveau 2 et les mises à niveau électriques au Canada.',
    'knowledge.resource2Button': 'En savoir plus',
    'knowledge.resource3Title': 'Plus de ressources à venir',
    'knowledge.resource3Desc': 'Des guides et documents supplémentaires sont en cours de développement. Revenez bientôt pour de nouvelles ressources.',
    'knowledge.faqTitle': 'Des questions?',
    'knowledge.faqDesc': 'Trouvez des réponses aux questions courantes sur les véhicules électriques et notre plateforme.',
    'knowledge.faqButton': 'En savoir plus sur nous',
    
    // Stakeholder Page
    'stakeholder.label': 'Communauté',
    'stakeholder.pageTitle': 'Engagement des Parties Prenantes',
    'stakeholder.pageSubtitle': 'Connecter les communautés, industries et institutions pour accélérer la transition vers la mobilité électrique.',
    'stakeholder.groupsTitle': 'Qui nous servons',
    'stakeholder.consumersTitle': 'Consommateurs et propriétaires de VE',
    'stakeholder.consumersDesc': 'Donner aux individus les connaissances et outils pour prendre des décisions éclairées sur les véhicules électriques.',
    'stakeholder.consumersPoint1': 'Accès aux simulateurs de recharge et calculateurs de coûts',
    'stakeholder.consumersPoint2': 'Ressources éducatives sur la technologie VE',
    'stakeholder.consumersPoint3': 'Guide d\'installation de recharge à domicile',
    'stakeholder.industryTitle': 'Partenaires industriels',
    'stakeholder.industryDesc': 'Collaborer avec les secteurs automobile et énergétique pour faire avancer l\'adoption des VE.',
    'stakeholder.industryPoint1': 'Outils de planification d\'infrastructure',
    'stakeholder.industryPoint2': 'Opportunités de collaboration de recherche',
    'stakeholder.industryPoint3': 'Analyses basées sur les données des tendances VE',
    'stakeholder.educationTitle': 'Institutions éducatives',
    'stakeholder.educationDesc': 'Soutenir la recherche académique et former la prochaine génération d\'experts VE.',
    'stakeholder.educationPoint1': 'Ressources de développement de programmes',
    'stakeholder.educationPoint2': 'Programmes de partenariat de recherche',
    'stakeholder.educationPoint3': 'Initiatives d\'engagement étudiant',
    'stakeholder.governmentTitle': 'Gouvernement et décideurs',
    'stakeholder.governmentDesc': 'Fournir des données et analyses pour soutenir des politiques VE basées sur des preuves.',
    'stakeholder.governmentPoint1': 'Outils d\'évaluation d\'impact',
    'stakeholder.governmentPoint2': 'Soutien à la planification d\'infrastructure',
    'stakeholder.governmentPoint3': 'Ressources de recommandations politiques',
    'stakeholder.involvedTitle': 'Impliquez-vous',
    'stakeholder.feedbackTitle': 'Partagez vos commentaires',
    'stakeholder.feedbackDesc': 'Aidez-nous à améliorer notre plateforme en partageant votre expérience et suggestions.',
    'stakeholder.feedbackButton': 'Contactez-nous',
    'stakeholder.partnerTitle': 'Devenez partenaire',
    'stakeholder.partnerDesc': 'Intéressé par une collaboration sur la recherche VE ou des initiatives éducatives?',
    'stakeholder.partnerButton': 'Visiter Smart Grid Lab',
    'stakeholder.ctaTitle': 'Prêt à faire un impact?',
    'stakeholder.ctaDesc': 'Explorez nos ressources et outils pour commencer votre voyage vers un transport durable.',
    'stakeholder.ctaButton': 'Explorer les ressources',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'fr' ? 'fr' : 'en') as Language;
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
